### ISSUE TITLE
How to increase a bass

### ISSUE THREAD

**Issue by nagayev** [paarthmadan/bass-boost#1]
How to increase a bass?

**Comment by paarthmadan** [comment]
Hey! I used a quick and dirty approximation to isolate the bass line of the given track. 
1) Determined the mean of the waveform, to deduce an estimate of the centre point. 
`est_mean = np.mean(sample_track)`
2) Deduce the standard deviation. 
`est_std = 3 * np.std(sample_track) / (math.sqrt(2))`
3) Use the difference between the axis of centre, and SD, to isolate the bass of the track.
`bass_factor = int(round((est_std - est_mean) * 0.005))`
4) Use a low pass filter to assign the bass to a separate track, which is then accentuated (louder) and added on to the original attenuated (quieter) track.
`filtered = sample.low_pass_filter(bass_line_freq(sample.get_array_of_samples()))`
`combined = (sample - attenuate_db).overlay(filtered + accentuate_db)`
NOTE: I am certain there's a mathematical approach to accurately isolate a bass line, this is just my quick approximation.
